services:
  - type: web
    name: yt-sub-tool
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: HARD_TIMEOUT_SEC
        value: "900"
      - key: STALL_TIMEOUT_SEC
        value: "300"
      # optional:
      # - key: PROXY
      #   value: ""
      # - key: COOKIES_PATH
      #   value: "/opt/render/project/src/cookies.txt"
    packages:
      - ffmpeg
    disk:
      name: jobs
      mountPath: /opt/render/project/src/jobs
      sizeGB: 2
