name: youtube-subtitle-app

# Where the code lives
services:
  - name: flask-service
    type: web
    runtime: python3.10
    region: europe  # pick closest (europe, sanfrancisco, singapore, etc.)
    instance_type: free   # ✅ stays free

    # Build & install ffmpeg + Python deps
    build:
      build_command: |
        apt-get update && apt-get install -y ffmpeg
        pip install -r requirements.txt

    # Start Flask (use your app.py)
    run:
      command: python app.py
      env:
        PORT: "8080"

    # Expose HTTP port
    ports:
      - port: 8080
        http: true

    # Optional: add your cookies secret here
    env:
      COOKIES_B64: ${COOKIES_B64}   # set this in Koyeb "Secrets"
