# render.yaml
services:
  - type: web
    name: yt-auto-subs
    env: docker
    plan: starter  # pick your plan
    branch: main
    disk:
      name: data
      mountPath: /data
      sizeGB: 10
    autoDeploy: true
    envVars:
      - key: HF_HOME
        value: /data/hf-cache
      - key: JOBS_DIR
        value: /data/jobs
      - key: DEFAULT_MODEL
        value: small
      - key: RES_OPTIONS
        value: use-vc attempts:2 timeout:3
      # optional:
      # - key: PROXY
      #   value: http://USER:PASS@HOST:PORT
    startCommand: >
      bash -lc 'echo -e "nameserver 1.1.1.1\nnameserver 8.8.8.8" >/etc/resolv.conf;
      export RES_OPTIONS="use-vc attempts:2 timeout:3";
      python app.py'
