services:
  - type: web
    name: clipper
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DEFAULT_MODEL
        value: small
      - key: HF_HOME
        value: /tmp/hf
      - key: JOBS_DIR
        value: /tmp/jobs
      # Optional (helps with "confirm you're not a bot"):
      # - key: PROXY
      #   value: http://user:pass@host:port
      # - key: YTDLP_EXTRA
      #   value: --extractor-args "youtube:player_client=android"
